import type { MonthlyMetricInput } from "./supabase";

/** Historical rows transcribed from WGI Podcast Reporting Input sheet */
export const SEED_MONTHS: MonthlyMetricInput[] = [
  {
    month_end: "2024-09-30",
    yt_views: 62,
    yt_watch_time_hrs: 3.7,
    yt_avg_view_duration_min: 3.6,
    yt_avg_pct_viewed: 16.5,
    yt_unique_viewers: 36,
    yt_clip_views: 0,
    yt_top_clip: "3: SEO",
    yt_top_episode: "9",
    apple_followers: 9,
    apple_net_new_followers: 9,
    apple_listeners: 10,
    apple_engaged_listeners: 9,
    apple_plays: 103,
    apple_hours_listened: 7,
    apple_top_episode: "2: Websites",
    spotify_followers: 15,
    spotify_net_new_followers: 15,
    spotify_plays: 54,
    spotify_streams_60s: 39,
    spotify_listeners: 24,
    spotify_impressions: 0,
    spotify_hours_played: 0,
    spotify_top_episode: "4: Video",
    notes: "",
  },
  {
    month_end: "2024-10-31",
    yt_views: 70,
    yt_watch_time_hrs: 6.5,
    yt_avg_view_duration_min: 5.6,
    yt_avg_pct_viewed: 21.6,
    yt_unique_viewers: 29,
    yt_clip_views: 1051,
    yt_top_clip: "Clip: Ep. 3 | Is SEO Dead?",
    yt_top_episode: "8: AI Content",
    apple_followers: 17,
    apple_net_new_followers: 8,
    apple_listeners: 11,
    apple_engaged_listeners: 8,
    apple_plays: 85,
    apple_hours_listened: 7,
    apple_top_episode: "7: INBOUND",
    spotify_followers: 22,
    spotify_net_new_followers: 7,
    spotify_plays: 109,
    spotify_streams_60s: 91,
    spotify_listeners: 38,
    spotify_impressions: 622,
    spotify_hours_played: 0,
    spotify_top_episode: "5: Sales Automation",
    notes: "",
  },
  {
    month_end: "2024-11-30",
    yt_views: 36,
    yt_watch_time_hrs: 5,
    yt_avg_view_duration_min: 8.3,
    yt_avg_pct_viewed: 32.7,
    yt_unique_viewers: 22,
    yt_clip_views: 515,
    yt_top_clip: 'Clip Ep 8: What does it mean to be the "human behind AI content?"',
    yt_top_episode: "9: ESOP Website",
    apple_followers: 17,
    apple_net_new_followers: 0,
    apple_listeners: 9,
    apple_engaged_listeners: 6,
    apple_plays: 26,
    apple_hours_listened: 3,
    apple_top_episode: "9: ESOP Website",
    spotify_followers: 23,
    spotify_net_new_followers: 1,
    spotify_plays: 28,
    spotify_streams_60s: 18,
    spotify_listeners: 18,
    spotify_impressions: 501,
    spotify_hours_played: 0,
    spotify_top_episode: "9: ESOP Website",
    notes: "",
  },
  {
    month_end: "2024-12-31",
    yt_views: 36,
    yt_watch_time_hrs: 4.1,
    yt_avg_view_duration_min: 6.8,
    yt_avg_pct_viewed: 25.2,
    yt_unique_viewers: 21,
    yt_clip_views: 505,
    yt_top_clip: "Clips from Ep 10 both have 497 views",
    yt_top_episode: "10: Brand Awareness",
    apple_followers: 20,
    apple_net_new_followers: 3,
    apple_listeners: 10,
    apple_engaged_listeners: 7,
    apple_plays: 54,
    apple_hours_listened: 7,
    apple_top_episode: "8: AI Content",
    spotify_followers: 23,
    spotify_net_new_followers: 0,
    spotify_plays: 24,
    spotify_streams_60s: 20,
    spotify_listeners: 14,
    spotify_impressions: 408,
    spotify_hours_played: 0,
    spotify_top_episode: "11: Content Strategy",
    notes: "",
  },
  {
    month_end: "2025-01-31",
    yt_views: 33,
    yt_watch_time_hrs: 2,
    yt_avg_view_duration_min: 3.33,
    yt_avg_pct_viewed: 14.7,
    yt_unique_viewers: 23,
    yt_clip_views: 701,
    yt_top_clip: "12: AI in Mfg #1",
    yt_top_episode: "12: AI in Mfg",
    apple_followers: 21,
    apple_net_new_followers: 1,
    apple_listeners: 11,
    apple_engaged_listeners: 7,
    apple_plays: 51,
    apple_hours_listened: 5,
    apple_top_episode: "13: State of WI Mfg",
    spotify_followers: 26,
    spotify_net_new_followers: 3,
    spotify_plays: 35,
    spotify_streams_60s: 25,
    spotify_listeners: 24,
    spotify_impressions: 480,
    spotify_hours_played: 0,
    spotify_top_episode: "12: AI in Mfg",
    notes: "",
  },
  {
    month_end: "2025-02-28",
    yt_views: 39,
    yt_watch_time_hrs: 4.3,
    yt_avg_view_duration_min: 6.6,
    yt_avg_pct_viewed: 26.9,
    yt_unique_viewers: 26,
    yt_clip_views: 40,
    yt_top_clip: "N/a",
    yt_top_episode: "14: Brand Evangelism",
    apple_followers: 24,
    apple_net_new_followers: 3,
    apple_listeners: 14,
    apple_engaged_listeners: 10,
    apple_plays: 44,
    apple_hours_listened: 6,
    apple_top_episode: "14: Brand Evangelism",
    spotify_followers: 30,
    spotify_net_new_followers: 7,
    spotify_plays: 42,
    spotify_streams_60s: 33,
    spotify_listeners: 27,
    spotify_impressions: 439,
    spotify_hours_played: 0,
    spotify_top_episode: "14: Brand Evangelism",
    notes: "",
  },
  {
    month_end: "2025-03-31",
    yt_views: 61,
    yt_watch_time_hrs: 3.2,
    yt_avg_view_duration_min: 3.2,
    yt_avg_pct_viewed: 9.3,
    yt_unique_viewers: 49,
    yt_clip_views: 231,
    yt_top_clip: "18: AI should work for you, no coding required",
    yt_top_episode: "18 (1 view over ep17)",
    apple_followers: 25,
    apple_net_new_followers: 1,
    apple_listeners: 8,
    apple_engaged_listeners: 5,
    apple_plays: 37,
    apple_hours_listened: 5,
    apple_top_episode: "17: Podcasting",
    spotify_followers: 31,
    spotify_net_new_followers: 1,
    spotify_plays: 32,
    spotify_streams_60s: 19,
    spotify_listeners: 24,
    spotify_impressions: 574,
    spotify_hours_played: 0,
    spotify_top_episode: "17: Podcasting",
    notes: "",
  },
  {
    month_end: "2025-04-30",
    yt_views: 98,
    yt_watch_time_hrs: 12.2,
    yt_avg_view_duration_min: 7.5,
    yt_avg_pct_viewed: 26.8,
    yt_unique_viewers: 51,
    yt_clip_views: 381,
    yt_top_clip: "20: Intro",
    yt_top_episode: "19: Andy Pt 1",
    apple_followers: 26,
    apple_net_new_followers: 1,
    apple_listeners: 13,
    apple_engaged_listeners: 9,
    apple_plays: 73,
    apple_hours_listened: 6,
    apple_top_episode: "19 & 20 almost identical metrics",
    spotify_followers: 31,
    spotify_net_new_followers: 0,
    spotify_plays: 62,
    spotify_streams_60s: 44,
    spotify_listeners: 15,
    spotify_impressions: 654,
    spotify_hours_played: 12,
    spotify_top_episode: "19 & 20 almost identical metrics",
    notes: "",
  },
  {
    month_end: "2025-05-31",
    yt_views: 69,
    yt_watch_time_hrs: 6.7,
    yt_avg_view_duration_min: 5.5,
    yt_avg_pct_viewed: 19.7,
    yt_unique_viewers: 47,
    yt_clip_views: 307,
    yt_top_clip: "Ep 22 Clip: Why AI Can't Fix Bad Data",
    yt_top_episode: "21: How Smart B2B Marketers Win with Email, Personalization, and AI",
    apple_followers: 28,
    apple_net_new_followers: 2,
    apple_listeners: 7,
    apple_engaged_listeners: 7,
    apple_plays: 42,
    apple_hours_listened: 5,
    apple_top_episode: "Ep 20: AI, Analytics, and Future-Proof Content Strategy with Andy Crestodina",
    spotify_followers: 32,
    spotify_net_new_followers: 1,
    spotify_plays: 34,
    spotify_streams_60s: 26,
    spotify_listeners: 22,
    spotify_impressions: 549,
    spotify_hours_played: 6,
    spotify_top_episode: "Ep 21: How Smart B2B Marketers Win with Email, Personalization, and AI",
    notes: "",
  },
  {
    month_end: "2025-06-30",
    yt_views: 69,
    yt_watch_time_hrs: 3.5,
    yt_avg_view_duration_min: 3.04,
    yt_avg_pct_viewed: 10.2,
    yt_unique_viewers: 43,
    yt_clip_views: 523,
    yt_top_clip: "Ep 23 Clip: Buy Back Your Time with Free AI Tools",
    yt_top_episode: "Ep 23: Experience Inbound 2025 Recap",
    apple_followers: 30,
    apple_net_new_followers: 2,
    apple_listeners: 12,
    apple_engaged_listeners: 7,
    apple_plays: 50,
    apple_hours_listened: 5,
    apple_top_episode: "Ep 23: Experience Inbound 2025 Recap",
    spotify_followers: 32,
    spotify_net_new_followers: 0,
    spotify_plays: 31,
    spotify_streams_60s: 13,
    spotify_listeners: 21,
    spotify_impressions: 398,
    spotify_hours_played: 3,
    spotify_top_episode: "Ep 23: Experience Inbound 2025 Recap",
    notes: "",
  },
  {
    month_end: "2025-07-31",
    yt_views: 52,
    yt_watch_time_hrs: 2.8,
    yt_avg_view_duration_min: 3.11,
    yt_avg_pct_viewed: 19.6,
    yt_unique_viewers: 39,
    yt_clip_views: 441,
    yt_top_clip: 'Ep 25: MINI RECAP Clip — "Why AI Can\'t Replace First-Hand Experience"',
    yt_top_episode: "Ep 026: Understanding AI Agents & Their Potential",
    apple_followers: 34,
    apple_net_new_followers: 4,
    apple_listeners: 13,
    apple_engaged_listeners: 9,
    apple_plays: 33,
    apple_hours_listened: 3,
    apple_top_episode: "Ep 19: Andy Crestodina's Guide to Winning the Content Marketing Marathon",
    spotify_followers: 33,
    spotify_net_new_followers: 1,
    spotify_plays: 20,
    spotify_streams_60s: 12,
    spotify_listeners: 6,
    spotify_impressions: 248,
    spotify_hours_played: 3,
    spotify_top_episode: "Ep 22: Mastering the Fundamentals of Growth",
    notes: "",
  },
  {
    month_end: "2025-08-31",
    yt_views: 91,
    yt_watch_time_hrs: 11.5,
    yt_avg_view_duration_min: 7.35,
    yt_avg_pct_viewed: 24.8,
    yt_unique_viewers: 64,
    yt_clip_views: 385,
    yt_top_clip: "Ep 27 Clip: Turning Your Premise Into a Buyer's Narrative",
    yt_top_episode: "Ep 027: Resonance Over Reach",
    apple_followers: 34,
    apple_net_new_followers: 0,
    apple_listeners: 8,
    apple_engaged_listeners: 4,
    apple_plays: 27,
    apple_hours_listened: 3,
    apple_top_episode: "",
    spotify_followers: 33,
    spotify_net_new_followers: 0,
    spotify_plays: 15,
    spotify_streams_60s: 9,
    spotify_listeners: 8,
    spotify_impressions: 172,
    spotify_hours_played: 3,
    spotify_top_episode: "Ep 027: Resonance Over Reach",
    notes: "",
  },
  {
    month_end: "2025-09-30",
    yt_views: 112,
    yt_watch_time_hrs: 8.7,
    yt_avg_view_duration_min: 4.39,
    yt_avg_pct_viewed: 21.2,
    yt_unique_viewers: 53,
    yt_clip_views: 528,
    yt_top_clip: "Ep 29 Clip: Buyer Behavior",
    yt_top_episode: "Ep 29 Bonus: Embracing Human-Powered Marketing in the AI Era",
    apple_followers: 35,
    apple_net_new_followers: 1,
    apple_listeners: 5,
    apple_engaged_listeners: 3,
    apple_plays: 51,
    apple_hours_listened: 5,
    apple_top_episode: "Ep 29 Bonus: Embracing Human-Powered Marketing in the AI Era",
    spotify_followers: 35,
    spotify_net_new_followers: 2,
    spotify_plays: 24,
    spotify_streams_60s: 23,
    spotify_listeners: 9,
    spotify_impressions: 280,
    spotify_hours_played: 3,
    spotify_top_episode: "Ep 29: What Inbound 2025 Taught Us About AI, Search, and the New Buyer",
    notes: "",
  },
  {
    month_end: "2025-10-31",
    yt_views: 53,
    yt_watch_time_hrs: 4.3,
    yt_avg_view_duration_min: 4.54,
    yt_avg_pct_viewed: 17.6,
    yt_unique_viewers: 31,
    yt_clip_views: 12,
    yt_top_clip: "Ep 17 Clip: Creating Synergy in Your Marketing Strategy",
    yt_top_episode: "Ep 30: Zero Click, AI, & the New Search Reality",
    apple_followers: 35,
    apple_net_new_followers: 0,
    apple_listeners: 6,
    apple_engaged_listeners: 0,
    apple_plays: 33,
    apple_hours_listened: 3,
    apple_top_episode: "Ep 30: Zero-Click, AI, & the New Search Reality",
    spotify_followers: 35,
    spotify_net_new_followers: 1,
    spotify_plays: 31,
    spotify_streams_60s: 21,
    spotify_listeners: 10,
    spotify_impressions: 315,
    spotify_hours_played: 5,
    spotify_top_episode: "Ep 30: Zero-Click, AI, & the New Search Reality",
    notes: "",
  },
  {
    month_end: "2025-11-30",
    yt_views: 44,
    yt_watch_time_hrs: 5,
    yt_avg_view_duration_min: 6.51,
    yt_avg_pct_viewed: 23.2,
    yt_unique_viewers: 27,
    yt_clip_views: 170,
    yt_top_clip: "Ep 31 Clip: Experimentation Provides New Data",
    yt_top_episode: "Ep 31: How Falcon Rebuilt Industrial AI Search Visibility",
    apple_followers: 31,
    apple_net_new_followers: -4,
    apple_listeners: 4,
    apple_engaged_listeners: 0,
    apple_plays: 48,
    apple_hours_listened: 4,
    apple_top_episode: "Ep 31: How Falcon Rebuilt Industrial AI Search Visibility",
    spotify_followers: 35,
    spotify_net_new_followers: 0,
    spotify_plays: 23,
    spotify_streams_60s: 12,
    spotify_listeners: 7,
    spotify_impressions: 154,
    spotify_hours_played: 4,
    spotify_top_episode: "Ep 30: Zero-Click, AI, & the New Search Reality",
    notes: "",
  },
];
